apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinsln
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkinsln
  template:
    metadata:
      labels:
        app: jenkinsln
    spec:
      containers:
      - name: jenkinsln
        image: aheshalagu/jenkinsln
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: jenkinsln
spec:
  type: NodePort
  selector:
    app: jenkinsln
  ports:
  - port: 3333
    targetPort: 3000


